# This workflow will generate a distribution and upload it to PyPI

name: Publish Alpha Build
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'version.py'

jobs:
  build_and_publish_pypi:
    uses: neongeckocom/.github/.github/workflows/publish_alpha_release.yml@FEAT_CommonWorkflows
    secrets: inherit
  build_and_publish_docker:
    needs: build_and_publish_pypi
    uses: neongeckocom/.github/.github/workflows/publish_docker.yml@FEAT_CommonWorkflows
    secrets: inherit
    with:
      base_tag: base
      extra_tag: default_model