# This workflow will generate a release distribution and upload it to PyPI

name: Publish Build and GitHub Release
on:
  push:
    branches:
      - master

jobs:
  publish_alpha_release:
    uses: neongeckocom/.github/.github/workflows/publish_stable_release.yml@master
    secrets: inherit
    with:
      publish_prerelease: true

  build_and_publish_docker:
    needs: build_and_publish_pypi_and_release
    uses: neongeckocom/.github/.github/workflows/publish_docker.yml@master
    secrets: inherit
    with:
      base_tag: base
      extra_tag: default_model
